# Generated by Django 2.2 on 2021-01-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scippetmodel',
            name='date',
        ),
    ]
